## cachematrix.R
## v1.0
##
## The result of the following two functions is to take a square matrix,
## solve for its inverse and cache it, so that the next time it needs to be
## referenced, it does not need to be recalculated, and can simply be
## retrieved from within the vector its stored in.

## makeCacheMatrix takes a square matrix as an argument, and returns a list
## of the following functions get, setinv, and getinv

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  ## get returns the original matrix
  get <- function() x
  ## setinv sets the argument passed to it to a vector labeled m within the
  ## environment
  setinv <- function(inv) m <<- inv
  ## getinv returns the vector labeled m within the environment
  getinv <- function() m
  ## creates a list of three named get, setinv, and getinv that are associated
  ## to the three functions defined similiarly above
  list( get = get,
        setinv = setinv,
        getinv = getinv)
}

## cacheSolve takes the list generated by makeCacheMatrix as an argument,
## calculates and stores the inverse of the original matrix, and returns it.
## If the inverse is already calculated, and stored, the function returns
## the value from the store without calculating it.

cacheSolve <- function(x) {
  ## Check to see if the inverse value is stored
  m <- x$getinv()
  if(!is.null(m)) {
    ## If stored, return it from the stored value
    message("getting cached data")
    return(m)
  }
  ## If not stored, get the original matrix using the get function
  data <- x$get()
  ## Use solve to calculate the inverse
  m <- solve(data)
  ## Cache the inverse to vector m in the environment
  x$setinv(m)
  ## Return the calculated inverse
  m
}
